Mobile menu
codewithed/portfolio-website pull request #12
Opened 2022-07-27 20:48 UTC by codewithed

## Created a pop-up menu for the nav elements.
- Used javascript to add functionality of the pop-up menu
- Used appropriate styling for the pop-up menu according to the figma template 

**NB: My coding partner was not present so I did it as a solo project**

2022-07-27 22:22 UTC, codecaiine requested changes
Hi @codewithed , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Good use of gitflow :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-27 22:22 UTC, codecaiine commented on index.html
> +            </nav>
- [ ] Good job so far your menu works :+1:  but there are some issues you need to address with your menu option. :cry:  Please try to adjust the spacing `padding/margin` between your different menu options **portfolio/ contact / About**  to have the same similar to Figma template :smile: 

### Your design
![Screenshot from 2022-07-27 22-03-09](https://user-images.githubusercontent.com/6615394/181380845-2e6a730b-e737-4800-8fe7-5397404118ca.png)

### Figma
![Screenshot from 2022-07-27 22-07-25](https://user-images.githubusercontent.com/6615394/181380990-5b5e2b1a-af06-4a2c-845a-9d9a6a1436fe.png)

2022-07-27 22:22 UTC, codecaiine commented on index.html
> +                <ul id="primary-navigation" data-visible="false" class="primary-navigation">
- [ ] Please adjust your menu list position to have the same similar to the Figma template because it is important to stick the design as much as possible  :+1: 
You can check the screenshot below to compare :arrow_down: 

### Your design
![Screenshot from 2022-07-27 22-09-24](https://user-images.githubusercontent.com/6615394/181381560-f9e68623-7baf-451f-b730-b7026ef59a71.png)

### Figma
![Screenshot from 2022-07-27 22-09-06](https://user-images.githubusercontent.com/6615394/181381564-9dbb10c6-2031-41a5-ba85-69abc5991537.png)

2022-07-27 22:22 UTC, codecaiine commented on index.js
> +});
- [ ] When we click (or tap) any option of the mobile menu, the mobile menu should disappear, but in your case, the mobile menu is still visible even if is leading to the option. Please fix it in order to give the user a great experience :smile: 
[Screencast from 07-27-2022 09:56:57 PM.webm](https://user-images.githubusercontent.com/6615394/181382393-2a7d5f1a-5b20-43b2-8089-7224d0c628e0.webm)

2022-07-28 09:28 UTC, Nemwel-Boniface approved these changes
## Hello @codewithed               :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for making the changes requested by the previous reviewer good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-28 09:39 UTC, merged