Desktop version
codewithed/portfolio-website pull request #7
Opened 2022-07-15 09:53 UTC by codewithed

Completed the following tasks for the desktop version:

Added a media query to implement mobile-first responsive design
Added appropriate images for certain elements
Added a nav-bar for the header section
Removed hamburger icon for desktop-version
Added appropriate styling in accordance with the template provided.

2022-07-15 11:34 UTC, codecaiine requested changes
Hi @codewithed , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Good use of Gitflow :heavy_check_mark: 
- Commits are meaningful :heavy_check_mark: 
- Clean code :heavy_check_mark:  

## Required Changes ♻️

- [x] You are doing well however make sure to stick to the design as much as possible (e.g., font, colors, images, text, margins) using :+1: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-15 11:34 UTC, codecaiine commented on index.html
>          <section class="works grid-container">
- [ ] Your project section has white color as `background-color` . Please use a `background-color: grey` to make it looks similar to the Figma template :smile: 

### Figma template
![Screenshot from 2022-07-15 11-01-27](https://user-images.githubusercontent.com/6615394/179211441-ba3a8eda-e74b-44a2-90c8-ddf529eda102.png)

### Your work
![Screenshot from 2022-07-15 11-01-02](https://user-images.githubusercontent.com/6615394/179211447-ba7219cd-f965-411e-94a0-217b7b440262.png)

- [ ] Please make sure that your project's picture and the project's description, switch places with each  as you can see on Figma template :+1:

2022-07-15 11:34 UTC, codecaiine commented on index.html
>          <section class="myself">
- [ ] Please make sure that the left part of your about myself takes 40% and the right one the remaining 60% of the page's width. Kindly alter it so it looks similar to the Figma design :+1: 

- [ ] Your experience description after about myself title looks bigger compared to Figma template, please make that you are using the correct  `font-size`. :+1: 

- [ ] Please make sure that your 3 rows have drop-down menus for the Languages, Frameworks, and Skills. :smile: 

### Figma template
![Screenshot from 2022-07-15 11-14-05](https://user-images.githubusercontent.com/6615394/179213530-e8b74a21-fc60-458f-b921-b58399fc2276.png)

### Your project
![Screenshot from 2022-07-15 11-12-25](https://user-images.githubusercontent.com/6615394/179213532-217d8e20-faee-4d11-96f6-95bc6f9a6814.png)

2022-07-15 11:34 UTC, codecaiine commented on index.html
>                  </ul>
- [ ] Your social media links seem to have different styling compared to the Figma template, kindly change it so it looks similar to the Figma template :+1: 

### Your work
![Screenshot from 2022-07-15 11-27-03](https://user-images.githubusercontent.com/6615394/179214811-b1c1580d-2279-4c7a-9d9f-0e77ab9aa503.png)

### Figma template
![Screenshot from 2022-07-15 11-26-44](https://user-images.githubusercontent.com/6615394/179214815-acb661d5-8fb6-45c6-a717-7e9716d296b7.png)

2022-07-16 20:10 UTC, MeqdamAlqudah approved these changes
Hi @codewithed , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-16 20:22 UTC, merged